### ISSUE TITLE
Towards perfection - Startup item

### ISSUE THREAD

**Issue by ChuckRider** [j7126/OctoPrint-Dashboard#247] opened 2021-01-01 13:52 UTC
When I start a print the old info remains for the gcode, height, and layer percent until the first g1 command is executed.  In other words, the entire time that the system is homing and heating.
![Capture](https://user-images.githubusercontent.com/58782813/103439841-09a11b00-4c06-11eb-81ad-df261c2dc129.PNG)

**Comment by StefanCohen** [comment] 2021-01-01 14:35
Agreed.  I would personally even prefer to clear them all on print end when the job is complete with an option to keep them until the next print start.

**Comment by j7126** [comment] 2021-01-02 00:26
See #177

**Comment by j7126** [comment] 2021-01-11 07:26
duplicate of #177

**Closed by j7126** 2021-01-11 07:26 UTC
