### ISSUE TITLE
Dashboard is Causing GCode Scripts for Start/Stop Not to Run

### ISSUE THREAD

**Issue by condraka** [j7126/OctoPrint-Dashboard#316] opened 2021-11-16 01:52 UTC
Running Current Versions

Octoprint 1.7.2
Dashboard 1.19.5
OctoPi 0.18.0
Python 3.7.3
on a Rasp Pi 3B+ Rev 1.3

GCode Scripts are partially working with Dashboard Plugin Active.  Just updated this weekend to 1.19.5 Dashboard and it stopped working.  Program Related Scripts are not being run.  Non-Program Related Scripts are working.

WORKING:  
Serial Connection Established
Serial Connection Closed 
After Print Job Canceled

NOT WORKING:  
Before Print Job Starts
After Print Job Completes (Have Not Confirmed This fails since I cancel print after it starts wrong).
[octoprint-systeminfo-20211115132259.zip](https://github.com/j7126/OctoPrint-Dashboard/files/7542715/octoprint-systeminfo-20211115132259.zip)

See Errors:  2021-11-15 17:59:44,280  in above octoprint.log

GCODE Script trying to run:  Fail's after G90 Absolute Positioning with G1 X-4 Y-4 ; Move Off Table
Don't know if the minus axis moves for X/Y is causing a division by zero error.  

M109 ;Wait For Hot End Temperature
M190 ;Wait for Bed Temperature
G28 ;Home Position
G90 ;Absolute Positioning
G1 X-4 Y-4 ;Move off Table
G1 Z0 F3000 ;Move Z to 0
G92 E0 ;Set Extruder Position to 0
G1 F200 E20 ;Prime Extruder
G92 E0 ;Set Extruder Position to 0
G1 Z0.60 F1000 ;Move Head Above Table
G1 X5.0 Y0.0 F1000 ;Move Head to edge of print area
G1 X120.0 E9.0 F1000.0 ;Intro Line
G1 Y0.40 E9.0 F1000.0 ;Turn Around
G1 X5.0 E20.0 F1000.0 ; End Line

Thanks.

Carl Ondraka

**Comment by j7126** [comment] 2022-02-02 08:15
Hi, believe I have created a fix, please install the development branch by installing the plugin with the below url and let me know if the issue is fixed. 

`https://github.com/j7126/OctoPrint-Dashboard/archive/development.zip`

**Comment by condraka** [comment] 2022-02-07 04:02
Scripts are running as expected.  Fix has corrected script issues.  Thanks

Carl E. Ondraka

**Comment by alaorath** [comment] 2022-03-06 15:02
Has this change been merged to master?  I ran into the same issue.  octoprint.log filled with exceptions ("Error while processing hook dashboard for phase sending and command ") and no completed movement.

Even the default octoprint movement buttons did nothing but generate log errors:

> 2022-03-05 17:10:00,385 - octoprint.util.comm - ERROR - Error while processing hook dashboard for phase sending and command G0 Z1 F200:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4611, in _process_command_phase
    tags=tags,
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_dashboard/__init__.py", line 797, in process_gcode
    current_layer_progress = int((self.layer_moves / self.layer_move_array[self.current_layer]) * 100)
IndexError: list index out of range


Solution was to reboot the PI, after reboot everything seemed normal again.

Octoprint: 1.7.3
Python: 3.7.3
OctoPi: 0.17.0
Dashboard: 1.19.8

**Comment by j7126** [comment] 2022-03-10 07:43
> Has this change been merged to master?

@alaorath It has not yet, but will be included with the next release, coming soon.

**Closed** 2022-03-10 10:17 UTC
Labels: bug
