### ISSUE TITLE
The layer progress percentage and progress bar go haywire

### ISSUE THREAD

**Issue by TheLion** [j7126/OctoPrint-Dashboard#315] opened 2021-11-12 14:50 UTC
I know that this is a bit long but please take your time and fill in the following information as clearly and detailed as possible. It will shorten the time needed to understand and fix the issue significantly. Please also state versions clearly when applicable. "Latest version" doesn't help much.  

**Describe the bug**
The layer progress percentage and progress bar go haywire.

**To Reproduce**
Open Dashboard during print.

**Expected behavior**
I expected the correct percentage and progress bar to show.

**Screenshots**
A screenshot doesn't do it justice. so I made a short video ;-)

https://u.pcloud.link/publink/show?code=XZvHqUXZedGMK8TuD3YL8fY6FQkiPFkeaHDV

**Files (please attach the following Files or screenshots when applicable):**
I'm not able to upload the gcode file, not even when I simplify the name and use .txt as extention.

**OctoPrint server and Plugins:**
 - Platform: Raspberry Pi 4 Model B Rev 1.1
 - OS and version: Raspbian GNU/Linux 10 (buster)
 - OctoPrint version: OctoPrint 1.7.2
 - Python version [e.g. Python 3.9.0]
 - Dashboard version Dashboard 1.19.5

**Desktop (please complete the following information):**
 - Windows 10
 - Browser and version FireFox 94.0.1 and Chrome 95.0.4638.69
 - Slicer version PrusaSlicer 2.3.3+win64 and processed by ArcWelder

**Additional context**
I currently notice this only on one of my printers (running the same version of Dashboard, PrusaSlicer, ArcWelder, Octoprint and Raspbian and I printed the exact same gcode several times (a couple of weeks ago) with older versions of Dashboard and back then there were no issues. Haven't printed this gcode on the other printer yet.

**Comment by KixMan28** [comment] 2021-11-17 13:11
Have a similar issue issue. I am using the latest (1.19.5) version nad the layer numbers and the filament length are wrongly displayed. See attached picture:
![Uploading 2021-11-17 13_55_59-Start.jpg…]()

Could you please correct theses?

**Comment by StarNamer** [comment] 2021-11-17 17:02
Also 1.19.5. Looks like it not getting the layer info and the layer percentage calculation is way off...
![image](https://user-images.githubusercontent.com/1997874/142246984-89d7a5b3-af43-4475-873a-3d05cc51ac85.png)

**Comment by Guenni75** [comment] 2021-12-04 13:35
I have not one Layer and no height.
![image](https://user-images.githubusercontent.com/14917841/144711439-12c2a8b6-f4e5-41da-93b6-9e890106a0f9.png)

**Comment by steadyaero** [comment] 2021-12-06 18:39
My layers seem correct, but I too am experiencing wonky extruded filament length:
![image](https://user-images.githubusercontent.com/10160060/144902118-a725df03-0cc6-4362-a5ad-a26dbfa77b72.png)
Octoprint version: 1.7.2
Server OS: Windows 10 21H1
Dashboard version: 1.19.5
Python version: 3.10.0
Slicer: Creality Slicer 4.8.2-177
Printer: Creality Ender 3 V2

**Comment by j7126** [comment] 2021-12-11 09:57
Alright, sorry that I have taken so long to get to this issue. Can you please upload the gcode files that you were printing when you experienced the issue, and I will be able to take a look at it from there.

**Comment by TheLion** [comment] 2021-12-12 12:31
> Alright, sorry that I have taken so long to get to this issue. Can you please upload the gcode files that you were printing when you experienced the issue, and I will be able to take a look at it from there.

Sure. How do you want me to send the gcode to you? I wasn't able to upload it in this issue.

**Comment by j7126** [comment] 2021-12-12 13:17
> Sure. How do you want me to send the gcode to you? I wasn't able to upload it in this issue.

Hmm, you usually should be able to upload it here. Perhaps put it in a Pastebin?

**Comment by TheLion** [comment] 2021-12-13 13:29
> > Sure. How do you want me to send the gcode to you? I wasn't able to upload it in this issue.
> 
> Hmm, you usually should be able to upload it here. Perhaps put it in a Pastebin?

Upload doesn't work unfortunately. Maybe it is the size, it is 27Mb.

You can find the gcode file here: https://u.pcloud.link/publink/show?code=XZhCnNXZv3ir352ienjY7kLOeYXDYuvDn0cV

**Comment by TheLion** [comment] 2022-01-08 11:22
I just experienced the same issue. With a much smaller gcode file. 
If you want, I can share it.

**Comment by j7126** [comment] 2022-01-12 08:59
So regarding the extruded filament length issue which was mentioned in this thread, I have created a fix which will be released soon, for more info see #309

**Comment by j7126** [comment] 2022-01-12 09:02
also see #311

**Comment by j7126** [comment] 2022-01-12 09:04
Closing as duplicate of #311

**Closed by j7126** 2022-01-12 09:04 UTC
Labels: bug

**Comment by j7126** [comment] 2022-01-12 09:21
@TheLion can you please try with a fresh profile on your slicer (reset ALL settings to default). probably easiest to backup your slicer config files and then delete them to start from scratch. and then let me know if the issue persists.

**Comment by TheLion** [comment] 2022-01-14 11:18
> @TheLion can you please try with a fresh profile on your slicer (reset ALL settings to default). probably easiest to backup your slicer config files and then delete them to start from scratch. and then let me know if the issue persists. If the issue stops by doing that, can you please send me your slicer profile file that is having the issue

Sure, will do that and let you know what happened.
